import { createPost, getPost, getPosts, Post } from '../../support/api/jsonplaceholder';

describe('Posts API — JSONPlaceholder', () => {
  it('GET /posts returns posts with the correct shape', { tags: ['@smoke', '@regression'] }, () => {
    cy.fixture<Post[]>('api/posts').then((expected) => {
      getPosts().then((response) => {
        expect(response.status).to.eq(200);
        expect(response.body).to.have.length.greaterThan(0);

        const first = response.body[0];
        expect(first).to.have.all.keys(Object.keys(expected[0]));
        expect(first.id).to.be.a('number');
        expect(first.title).to.be.a('string').and.have.length.greaterThan(0);
        expect(first.userId).to.be.a('number');
      });
    });
  });

  it('GET /posts/1 returns the expected post', { tags: '@regression' }, () => {
    cy.fixture<Post>('api/post').then((expected) => {
      getPost(1).then((response) => {
        expect(response.status).to.eq(200);
        expect(response.body.id).to.eq(expected.id);
        expect(response.body.userId).to.eq(expected.userId);
        expect(response.body.title).to.be.a('string').and.have.length.greaterThan(0);
        expect(response.body.body).to.be.a('string').and.have.length.greaterThan(0);
      });
    });
  });

  it('POST /posts creates a new post and echoes the body', { tags: ['@smoke', '@regression'] }, () => {
    cy.fixture<Omit<Post, 'id'>>('api/post').then((post) => {
      createPost(post).then((response) => {
        expect(response.status).to.eq(201);
        expect(response.body.title).to.eq(post.title);
        expect(response.body.body).to.eq(post.body);
        expect(response.body.userId).to.eq(post.userId);
        expect(response.body.id).to.be.a('number');
      });
    });
  });

  it('POST /posts uses a UUID from cy.task() to guarantee a unique title', { tags: '@regression' }, () => {
    cy.task<string>('generateUuid').then((uuid) => {
      createPost({ title: `Post ${uuid}`, body: 'Generated by cy.task', userId: 1 }).then((response) => {
        expect(response.status).to.eq(201);
        expect(response.body.title).to.include(uuid);
      });
    });
  });
});
